### ISSUE TITLE
Error: Polygon Division Failed: float floor division by zero

### ISSUE THREAD

**Issue by denvercitizen9** [jonnyhuck/RFCL-PolygonDivider#18] opened 2022-06-14 22:55 UTC
UPDATE: SEE COMMENTS

Dr. Huck and team,

I was very excited about this plugin, however I have not quite been able to get it working as expected.  I am unsure if there is something I might be missing with my QGIS setup, or if there is something wrong with my polygon (attached).  The error I receive is:

**`Error: Polygon Division Failed: float floor division by zero`**

I have tried various methods for correcting this, but cannot seem to figure out what the issue is. This seems to be the same error as #17 but I've opened this issue because I am using the current version with the projected CRS requirement.

**QGIS version:**   
    3.22.7  

**Input Layer:**   
    I have tried each of the attached files  

**Number of Divisions:**  
    I have tried very small and very large numbers, but final target will be around 7000  

**Cut Direction/Tolerance**   
   I have tried all  

**Absorb Offc**  
   true  

**CRS**  
   I have tried a few under WGS84 without success.  Ultimate goal is [GeoJSON ](https://datatracker.ietf.org/doc/html/rfc7946) for which I may need to convert to a non-projected WGS84, but at least for getting this going I would be happy to use any that will allow for success.  

Additionally, while relatively new to GIS, I have had a long technical career and can possibly contribute to the project VIA a pull request if there are changes necessary to support my use case... though I am optimistic that there is something small I am overlooking, or that perhaps there is something missing from the polygon I am starting with.

I am attaching [PolygonDivider_FloatFloorDivisionIssue.zip](https://github.com/jonnyhuck/RFCL-PolygonDivider/files/8904356/PolygonDivider_FloatFloorDivisionIssue.zip) in the hope that perhaps there is something I am overlooking or there is a way to make this work.  Note I am attaching a **zip** file because github does not support the included **kml/kmz/shp** files (can upload to another service if you prefer).  

Very grateful for your time.  Please let me know if you need anything else to support this.

Thank you,
Daniel
Denver, Colorado

**Comment by denvercitizen9** [comment] 2022-06-15 01:26
I have learned that while I changed the QGIS view I did not save the layer.  I didn't want to go into the 'how' for doing that because I wasn't sure if there were multiple approaches, but did add a small comment to the README that I submitted in a PR which will hopefully help point others in the right direction.

**Leaving this issue OPEN because the fix implemented for issue #17 only looks at the CRS of the view, not the underlying data** (the error message added for #17 does not show up if the projected coordinates are being used in the project/layer, but the underlying data is still saved as geographical).

Not sure if you felt my PR comment could help clarify, but thought I would allow you to decide since your solution is at least partially coded.

**Comment by jonnyhuck** [comment] 2022-06-15 08:33
Hi @denvercitizen9, thanks very much for this, including the detailed report - I have merged your pull request and useful comment - longer term I need to haver a think about making a geographical version of this software I think, but this will certainly help for now!

More pressing is the issue around the warning - though I cannot replicate this issue (where simply projecting the view avoids the warning and leads to the error). Could you please check for me that you definitely have version 0.7 installed (the one where I added the warning)? If so, could you please send me a dataset and workflow that I can try and replicate?

Thanks again,

Jonny

**Comment by denvercitizen9** [comment] 2022-06-15 23:21
Great, and thanks for the fast turnaround!

My installed plugin version is 0.7

Here's a workflow that I can get to reproduce...

Using the attached file (can use the KMZ file from zip file in original message for this issue, but guessing this workflow would work for your files also), my first attempt at converting is:
`Error: : Polygon Division Failed: Whoops! The Polygon Divider requires a projected dataset - please save a copy with a projected CRS and try again.`

**The File Loads with the Saved CRS as:**
EPSG:4326
(causing expected error from divider)

**Change Layer CRS, but don't save a copy of the layer with updated CRS**
Right Click Layer > Layer CRS > Set To EPSG:32612 
Then, run the divider:
**`Error: Polygon Division Failed: float floor division by zero`**

I'm still new to all of this, but I think this error happens because the check to see if the correct format is being used happens in the program (so in that sense it is 'set' correctly) but the divider program references the saved file, which still has the incorrect default.

So... poor guys like me figure out how to update the polygon not realizing that it isn't just the current rendering that needs to be updated, but the actual file needs to be saved with the correct CRS.

In hindsight I realized the error messages says explicitly to "Save a copy" but in my fumbling through all of this I missed the nuance.  When I updated the CRS for the layer, I saved _the project_.  Because I got a different error I mistakenly thought I had solved the problem... but in reality I just figured out a creative way to avoid triggering the error message.

**Comment by jonnyhuck** [comment] 2022-06-16 07:42
Ah, I see what the issue is - what you are doing there is overriding the CRS of the layer without actually transforming it  (i.e. telling it that it is projected, when in fact it is not), this is a third alternative to actually transforming it (by saving a copy) or setting the CRS of the view (using the CRS menu in the bottom right of the screen. The effect is that it passes the test (because it thinks it is projected), but the algorithm still fails because the coordinates have not actually changed.

The snag here is that I don't think there is a robust way for us to validate if this has happened (because the layer thinks it has been projected, when in fact it has not, but the coordinates would still likely be valid values, so we can't simply rule them out based on the bounds of the projection). In a way it is irritating that QGIS makes it so easy to do this, as it is quite a misleading function for must users.

This might just have to be something that we deal with in more detail in the documentation and with a more specific error message for the divided by 0 error, unless you have any other ideas?

**Comment by denvercitizen9** [comment] 2022-06-18 15:08
I'm not very familiar with the model but I'm not seeing anything
immediately obvious.

I'm guessing that programmatically there might be a way to access the state
information in the object, or some more creative way to check the saved
file, but guessing the rabbit hole could go deep and/or it might not be
worth the payoff.

I'm also a proponent of "what thing could we do that is the least amount of
effort that could possibly work" and I'm all for documentation.  I added
the README comment hoping it may have been enough to point me in the right
direction.  More clarification in the error message could be helpful
(and/or, some type of "What to check if you get X error" reference).

**Comment by rodrigo-j-goncalves** [comment] 2023-12-22 10:09
I'm also getting ```CRITICAL    Error: : Polygon Division Failed: float floor division by zero``` message.
Anything can I do to help diagnose this?

**Comment by jonnyhuck** [comment] 2023-12-22 10:52
Hi Rodrigo - 

No problem - can you please confirm if the dataset you are tryiong to divide is projected? 

If so, can please you send me a link to the dataset that you are trying to divide please and I will test it?

**Comment by rodrigo-j-goncalves** [comment] 2023-12-22 11:54
Sure, [here](https://mega.nz/folder/3axFgZpY#BORkpKvUQT7ga88I1ElkKQ) you can find the QGIS project file and the layer to be divided. I tried to divide it into 200 parts. As far as I can tell, it is a projected CRS. I have many other layers that I would need to split into even larger numbers of parts (millions) so I am using this as a test case. Thanks so much for looking into this!

**Comment by jonnyhuck** [comment] 2023-12-22 16:33
OK, it looks like the problem is that your geojson file claims that it is using a projected coordinate system (EPSG::3118), but in fact this is not the case - you can see this if you open it in a text editor, it is clearly in degrees:

```
 [ -54.97624969482419, -34.947917938232436 ], [ -54.97624969482419, -34.948192596435547 ], [ -54.974861145019453, -34.948192596435547 ], ...
```

It is possible that this is the same issue (or one similar) as the one above (see [my exaplanation from 16th June 2022](https://github.com/jonnyhuck/RFCL-PolygonDivider/issues/18#issuecomment-1157341258)), but either way, the best way to fix it is probably something like this: 
1. open it in QGIS,
2.  right click -> Layer CRS and Set the CRS back to WGS84 (EPSG:4326), 
3. then right click again and export the file to a Shapefile - during this process you can select a new CRS (e.g,. EPSG::3118) and the export process will transform the layer.  

If you try to divide the resulting shapefile then it should work fine.

Is that any use?

**Comment by rodrigo-j-goncalves** [comment] 2023-12-23 10:03
Crap, that's embarrassing, yes I read all the previous discussions and made sure to save with a projected CRS. Actually, I exported the GEOJSON from QGIS! Weird that one can not trust the 'claimed' CRS.

Anyway, it worked perfectly fine, thanks so much for looking into this, and also thanks so much for this great plugin, it is a wonderful contribution!!

**Closed as completed** 2024-03-23 14:38 UTC
